apiVersion: v1
kind: Pod
metadata:
  name: startup
spec:
  containers:
  - name: startup
    image: kushagratandon12/smart_bank_backend:v1
    startupProbe:
      httpGet:
        path: /
        port: 80
      failureThreshold: 2
      successThreshold: 1
      periodSeconds: 5
      initialDelaySeconds: 0