apiVersion: apps/v1
kind: Deployment
metadata:
  name: sba-frontend-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sba-frontend
      release: v1
  template:
    metadata:
      labels:
        app: sba-frontend
        release: v1
    spec:
      containers:
      - image: kushagratandon12/smart_bank_fronend:nginx
        imagePullPolicy: IfNotPresent
        name: sba-frontend-app
        ports:
        - containerPort: 80
          name: nginx
        volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
      volumes:
        - name: nginx-config
          configMap:
            name: ambassador-nginx-config 
